### ISSUE TITLE
i5k adoption: apollo 1

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_apollo#55]
prior to i5k adoption, we need to figure out what is goign on with apollo 1.

the code is several different script executions, all commented out with instructions for different environments.  We need to discuss what is goign on here so i can abstract it.

**Comment by bradfordcondon** [comment]
please see https://github.com/isdapps/i5k-tripal/blob/b7ed8cb16f777a4a17ca72f537e80392b8ba2c5b/sites/all/modules/custom/web_apollo/web_apollo.admin.inc#L322-L340 for the code.

**Comment by bradfordcondon** [comment]
basically it runs `set_track_permissions.pl` and `add_user.pl` but those perl scripts arent in the server (i think its part of jbrowse..?) . My best guess is this is from when Apollo 1 and Tripal were on the same environment.  Does that sound like a good guess @childers ?

**Comment by bradfordcondon** [comment]
this is my mistake.  the python script uses `psycopg2` which is what sets up the remote connection.

This means we'll keep the python script for apollo 1 support.

**Comment by bradfordcondon** [comment]
ideally i can run this?

https://github.com/Coderx7/apollo-1

**Comment by bradfordcondon** [comment]
oops lol thats a driving platform.  lets try and find a jbrowse apollo docker....

**Comment by bradfordcondon** [comment]
ok i've constructed a minimal mock postgres docker with just the apollo 1 tables this script creates.
here's the built shell command for apollo 1, and the current error which appears unrelated.  

```
Traceback (most recent call last):
  File "/Users/bc/tripal/sites/all/modules/custom/tripal_apollo/bin/add_user.py", line 42, in <module>
    conn = psycopg2.connect('dbname=' + dbname + ' user=' + dbuser + ' host=' + host)
  File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "http://localhost:5433" to address: nodename nor servname provided, or not known

```

**Comment by bradfordcondon** [comment]
ok it looks like we need to separate out the port and the URL for psycopg2 to be happy.  Let's try and do that in the python script so we dont have to change our schema for apollo 1.

**Comment by bradfordcondon** [comment]
script as written doesnt use dbpass so i get a no password error.  

`conn = psycopg2.connect('dbname=' + dbname + ' user=' + dbuser + ' host=' + host)` . confusing, how would this work?

**Comment by bradfordcondon** [comment]
ok with that last hiccup overcome, the script runs!
```

postgres=# select * from users;
 user_id |     username     |    password
---------+------------------+-----------------
       1 | apollo1@ccom.com | Enlief2Bellwind
(1 row)

postgres=# select * from permissions;
 track_id | user_id | permission
----------+---------+------------
(0 rows)
```
so while we are creating the user, we arent adding the permissions unfortunately.

**Comment by bradfordcondon** [comment]
conclusions:

* I just need to insert some tracks for the above SQL to populate permissions.
* apollo 1 needs one instance/organism which i think we can support better (see #57 )
* the perl scripts are never executed.  **if that is true** then we can safely close this issue: we support apollo 1!
